module.exports = [
  'background.png',
  'background-extension.png',
  'background-extension-sunset.png',
  'background-extension-night.png',
  'hook.png',
  'block-rope.png',
  'block.png',
  'block-perfect.png',
  'home-cake-tower.png',
  'heart.png',
  'favicon.png',
  'drop-perfect.mp3',
  'drop.mp3',
  'drop-safe.wav',
  'sugar-rush.wav',
  'game-over.mp3',
  'rotate.mp3',
  'bgm.mp3',
  'zepto-1.1.6.min.js',
  ...[
    'strawberry',
    'chocolate',
    'lemon',
    'blueberry',
    'macaron',
    'star-sprinkle',
    'golden-caramel',
    'berry-jewel',
    'royal-macaron'
  ].map(name => `cakes/cake-${name}.png`),
  ...Array.from({ length: 8 }, (_, index) => `c${index + 1}.png`),
  ...Array.from({ length: 7 }, (_, index) => `f${index + 1}.png`)
]
