export const gameStartNow = 'GAME_START_NOW'
export const gameUserOption = 'GAME_USER_OPTION'
export const hardMode = 'HARD_MODE'

export const successCount = 'SUCCESS_COUNT'
export const failedCount = 'FAILED_COUNT'
export const perfectCount = 'PERFECT_COUNT'
export const gameScore = 'GAME_SCORE'
export const sugarRushRemaining = 'SUGAR_RUSH_REMAINING'
export const sugarRushLastTrigger = 'SUGAR_RUSH_LAST_TRIGGER'
export const sugarRushTransition = 'SUGAR_RUSH_TRANSITION'
export const runPromptQueue = 'RUN_PROMPT_QUEUE'
export const runPromptSeen = 'RUN_PROMPT_SEEN'
export const milestonesTriggered = 'MILESTONES_TRIGGERED'
export const targetsPrompted = 'TARGETS_PROMPTED'
export const milestoneReliefPending = 'MILESTONE_RELIEF_PENDING'
export const milestoneReliefRestore = 'MILESTONE_RELIEF_RESTORE'
export const towerDynamicsState = 'TOWER_DYNAMICS_STATE'
export const cakeRareQueue = 'CAKE_RARE_QUEUE'
export const cakeSessionNewStyle = 'CAKE_SESSION_NEW_STYLE'
export const cakeSessionNewIntroduced = 'CAKE_SESSION_NEW_INTRODUCED'
export const cakeSessionFeaturedStyle = 'CAKE_SESSION_FEATURED_STYLE'
export const cakeStylesSinceFeature = 'CAKE_STYLES_SINCE_FEATURE'
export const cakeKnownBag = 'CAKE_KNOWN_BAG'
export const cakeLastStyle = 'CAKE_LAST_STYLE'
export const cakeRunPerfects = 'CAKE_RUN_PERFECTS'

export const hookDown = 'HOOK_DOWN'
export const hookUp = 'HOOK_UP'
export const hookNormal = 'HOOK_NORMAL'

export const bgImgOffset = 'BACKGROUND_IMG_OFFSET_HEIGHT'
export const lineInitialOffset = 'LINE_INITIAL_OFFSET'
export const bgLinearGradientOffset = 'BACKGROUND_LINEAR_GRADIENT_OFFSET_HEIGHT'


export const blockCount = 'BLOCK_COUNT'
export const blockWidth = 'BLOCK_WIDTH'
export const blockHeight = 'BLOCK_HEIGHT'
export const cloudSize = 'CLOUD_SIZE'
export const ropeHeight = 'ROPE_HEIGHT'
export const flightCount = 'FLIGHT_COUNT'
export const flightLayer = 'FLIGHT_LAYER'
export const feedbackLayer = 'FEEDBACK_LAYER'

export const rotateRight = 'ROTATE_RIGHT'
export const rotateLeft = 'ROTATE_LEFT'
export const swing = 'SWING'
export const beforeDrop = 'BEFORE_DROP'
export const drop = 'DROP'
export const land = 'LAND'
export const out = 'OUT'

export const initialAngle = 'INITIAL_ANGLE'

export const bgInitMovement = 'BG_INIT_MOVEMENT'
export const hookDownMovement = 'HOOK_DOWN_MOVEMENT'
export const hookUpMovement = 'HOOK_UP_MOVEMENT'
export const lightningMovement = 'LIGHTNING_MOVEMENT'
export const tutorialMovement = 'TUTORIAL_MOVEMENT'
export const moveDownMovement = 'MOVE_DOWN_MOVEMENT'
